apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: my-app
spec:
  ports:
   - port: 27017
     targetPort: 27017
  clusterIP: None
  selector:
    app: my-app
    name: mongo-pod